services:
  ActionEaseKit\Base\Service\CurlService:
    class: ActionEaseKit\Base\Service\CurlService

  ActionEaseKit\Base\Service\RunCustomCommandService:
    class: ActionEaseKit\Base\Service\RunCustomCommandService
    arguments:
      - "@kernel"
